spaceadventure/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('spaceapp.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

spaceapp/urls.py
from django.urls import path
from . import views

app_name = 'spaceapp'

urlpatterns = [
    path('base/', views.base_page, name='base'),
    path('project/', views.project_page, name='project'),
    path('develops/', views.develops_page, name='develops'),
    path('feedback/', views.feedback_page, name='feedback'),
    path('GJ504b/', views.GJ504b_page, name='GJ504b'),
    path('gliese/', views.gliese_page, name='gliese'),
    path('kepler/', views.kepler_page, name='kepler'),
    path('nimro/', views.nimro_page, name='nimro'),
    path('prometheus/', views.prometheus_page, name='prometheus'),
    path('tanos/', views.tanos_page, name='tanos'),
    path('chimaira/', views.chimaira_page, name='chimaira'),
    path('search/', views.search_box_action, name='search'),
    ]

spaceapp/models.py
from django.db import models


class Font(models.Model):
    font_name = models.CharField(max_length=100)
    def __str__(self):
        return f'{self.font_name}'


class KeplerUser(models.Model):
    user_name = models.CharField(max_length=21)
    font = models.ForeignKey(Font, on_delete=models.PROTECT)

spaceapp/forms.py
from django import forms
from .models import KeplerUser


class KeplerUserForm(forms.ModelForm):
    class Meta:
        model = KeplerUser
        fields = ["user_name", "font"]
        widgets = {
            "user_name": forms.TextInput(attrs={"class": "form-select"}),
            "font": forms.Select(attrs={"class': 'form-select"}),
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

spaceapp/views.py
import json
import traceback

from django.http import HttpResponse
from django.shortcuts import render
from spaceapp.dto import OutputDTO, InputDTO
from spaceapp.forms import KeplerUserForm
from spaceapp.models import Font
from spaceapp.usecase import save_user_data, upper_string, usecase_get_all_fonts


# Весь блок генерирует страницы html
def base_page(request):
    return render(request, 'spaceapp/base.html')


def project_page(request):
    return render(request, 'spaceapp/project.html')


def develops_page(request):
    return render(request, 'spaceapp/develops.html')


def feedback_page(request):
    return render(request, 'spaceapp/feedback.html')


def GJ504b_page(request):
    return render(request, 'spaceapp/GJ504b_page.html')


def kepler_page(request):
    fonts = usecase_get_all_fonts()
    # Переменная form_data содержит данные введенные пользователем на странице
    if request.method == "POST":
        name = request.POST.get("user_name")
        font = request.POST.get("font")
        input_dto = InputDTO(name=name, font=font)
        result_upper_string = upper_string(input_dto)
        print("DTO", result_upper_string)

        # Дальше идет мой новый код с сохранением формы в джанго админ
        form = KeplerUserForm(request.POST)

        if form.is_valid():
            try:
                form.save()

            except Exception as e:
                print(f"❌ Ошибка при сохранении: {e}")
                print(f"Трассировка: {traceback.format_exc()}")

        else:
            print("❌ Форма невалидна")
            print("Ошибки:", form.errors.as_json())
            print("POST данные:", request.POST)

    else:
        form = KeplerUserForm()

    context = {
        "fonts": fonts,
        "form": form,
    }

    return render(request, 'spaceapp/kepler_page.html', context)


def gliese_page(request):
    return render(request, 'spaceapp/gliese_page.html')


def nimro_page(request):
    return render(request, 'spaceapp/nimro_page.html')


def prometheus_page(request):
    return render(request, 'spaceapp/prometheus_page.html')


def tanos_page(request):
    return render(request, 'spaceapp/tanos_page.html')


def chimaira_page(request):
    return render(request, 'spaceapp/chimaira_page.html')


# функция поиска по сайту
def search_box_action(request):
    if request.method == 'POST':
        txt = request.POST.get('txt')
        print(txt.find(''))
        return render(request, 'spaceapp/search.html')
    else:
        pass

# Написать техническое задание к этому проекту, что должно происходить на сайте

templates/ButtonPlayStop/index.html
<div class="button"></div>

templates/spaceapp/GJ504b_page.html
<!DOCTYPE html>
{% load static %}
<html lang="ru">
<head>
   <title>GJ504b_page</title>
   <meta charset="UTF-8">
   <meta http-equiv="X-UA-Compatible" content="ie=edge">
   <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no»"/>
   <link rel="shortcut icon" href="{% static 'img/favicon.png' %}" type="image/x-icon"/>
   <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/swiper@9/swiper-bundle.min.css" />
   <link rel="stylesheet" type="text/css" href="{% static 'css/style_gj504b_page.css' %}"/>
   <script src="https://kit.fontawesome.com/b99e675b6e.js"></script>
</head>
   <body>
    <div class="content-box">
    <header>
        <div class="All_header_menu">
            <div class="logo">
                <a href="{% url 'spaceapp:base' %}"><h1>ElectroCore Space Project</h1></a>
				</div>
            <div class="top_menu">
                <ul>
					<li><a href="{% url 'spaceapp:project' %}">Наш проект</a></li>
					<li><a href="{% url 'spaceapp:develops' %}">Разработки</a></li>
                    <li><a href="{% url 'spaceapp:feedback' %}">Обратная связь</a></li>
                </ul>
			</div>
		</div>
        <div class="wrapper">
            <div class="search_box">
                <div class="search_btn"><input type="image" src="{% static 'img/sear_icon.png' %}" alt="search" width="25px" height="25px"/></div>
                <input type="text" class="input_search" placeholder="Поиск">
            </div>
        </div>
	</header>
<div class="background_article">
    <div class="frame_article">
  <div class="article">
    <img src="{% static 'img/GJ504b_photo.png' %}" alt="GJ504b_photo"/>
    <p><u><b>На данный момент у нас отсутствуют изображения данной планеты, а представленное фото носит лишь иллюстративный характер.</b></u></p>
  <p>GJ504b - экзопланета в созвездии Дракон, принадлежащая к классу суперземель, в 560 световых годах от Земли. 
    Обращается вокруг желтого карлика Kepler-10. Год на Kepler-10c длится 45 земных дней.
    <p><b>Полет к планете GJ504b будет осуществлятся на новейшем корабле Prometheus-UX754ii.</p>
    <p>Сопровождение космического корабля Prometheus-UX754ii будет осуществлять искусственный интелект Chimaira, а также анализировать и передавать все данные по экспедиции.</p>
    <p>Высадка дронов и остальная необходимая работа для проведения данной экспедиции будет проводится в режиме онлайн.</p>
    <p>Для того чтобы ничего не пропустить заполните форму и мы сообщим Вам о начале трансляции!</b></p>
    <button class="show-modal" align="center">Подписаться на трансляцию</button>
    <div class="modal hidden">
        <button type="button" class="close-modal">&times;</button>
        <div class="modal_style">
            <form class="form">
              <h2 class="form_title">Ввод данных</h2>
              <div class="form_group">
                <input class="form_input" type="text" placeholder="Введите Ваше имя" align="center" maxlength="21">
                <input class="form_input" type="text" placeholder="Введите Ваш email или телефон" align="center">
                <label class="form_label"></label>
            <div class="send">
            <input type="submit" align="center" value="Отправить">
        </form>
      </div>
    </div>
    </div>
    </div>
    <div class="overlay hidden"></div>
    <script src="{% static 'js/script.js' %}" ></script>
    </div>
  </div>
</div>
<div class="footer_gj504b_page">
    <p>Вся информация, представленная на сайте, является вымышленной любые совпадния случайны.
        <p>Designed by SvPr1993</p>
        <p><img src="{% static 'img/logo.png' %}" alt="logo"width="20px" height="20px" style="margin-bottom: -2px"/>ElectroCore Space Project &copy</p>
        </div>
        <div class="images_footer"> 
            <a href="https://www.nasa.gov/"><img src="{% static 'img/nasa_logo.png' %}" alt="nasa" width="55px" height="55px"/></a>
            <a href="https://www.spaceappx.com/"><img src="{% static 'img/space_x_logo.png' %}" alt="space_x_logo" width="65px" height="65px"/></a>
            <a href="https://global.jaxa.jp/"><img src="{% static 'img/jaxa_logo.png' %}" alt="jaxa" width="55px" height="55px"/></a>
            <a href="https://www.esa.int/"><img src="{% static 'img/ESA_logo.png' %}" alt="ESA" width="75px" height="65px"/></a>
    </div>
</body>
</html>

templates/spaceapp/base.html
<!DOCTYPE html>
{% load static %}
<html lang="ru">
<head>
   <title>ElectroCore Space Project</title>
   <meta charset="UTF-8">
   <meta http-equiv="X-UA-Compatible" content="ie=edge">
   <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no»"/>
   <link rel="shortcut icon" href="{% static 'img/favicon.png' %}" type="image/x-icon"/>
   <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/swiper@9/swiper-bundle.min.css" />
   <link rel="stylesheet" type="text/css" href="{% static 'css/styles.css' %}"/>
   <script src="https://kit.fontawesome.com/b99e675b6e.js"></script>
</head>
   <body>
    <div class="content-box">
    <header>
        <div class="All_header_menu">
            <div class="logo">
                <a href="{% url 'spaceapp:base' %}"><h1>ElectroCore Space Project</h1></a>
				</div>
            <div class="top_menu">
                <ul>
					<li><a href="{% url 'spaceapp:project' %}">Наш проект</a></li>
					<li><a href="{% url 'spaceapp:develops' %}">Разработки</a></li>
                    <li><a href="{% url 'spaceapp:feedback' %}">Обратная связь</a></li>
                </ul>
			</div>
		</div>
        <div class="wrapper">
            <div class="search_box">
                <div class="search_btn"><input type="image" src="{% static 'img/sear_icon.png' %}" alt="search" width="25px" height="25px"/></div>
                <input type="search" class="input_search" placeholder="Поиск" font-size="15px">
            </div>
        </div>
	</header>
	<div class="background_base">
    <div class="advertisement">
		<p>Добро пожаловать на сайт нашего проекта!</p>
		<p>Наш проект сопровождает экспедиции на другие планеты и проводит исследовательские работы!</p>
		<p>Хотите вписать свое имя в эпоху космических открытий?</p>
		<p>Тогда переходите по ссылкам на экспедиции и заполните форму.</p>
	</div>
	<div class="middle_content_box">
		<div class="swiper mySwiper">
			<div class="swiper-wrapper">
				<div class = "swiper-slide">
				<a href="{% url 'spaceapp:gliese' %}"><img src="{% static 'img/Gliese581c.png' %}" alt="Gliese581c"/></a>
				</div>
				<div class="swiper-slide">
				<a href="{% url 'spaceapp:kepler' %}"><img src="{% static 'img/Kepler22.jpg' %}" alt="Kepler22"/></a>
				</div>
				<div class="swiper-slide">
				<a href="{% url 'spaceapp:GJ504b' %}"><img src="{% static 'img/PinkPlanetGJ504b.jpg' %}" alt="GJ504b"/></a>
				</div>
			   </div>
			</div>
		</div>
		<div class="vertical_content_box">
			<div class="swiper-wrapper-vertical">
				<div class="circular-bar">
				<div class="swiper-container">
				<div class="swiper-slide-vertical"><img src="{% static 'img/Gliese581c.png' %}" alt=""></div>
				<div class="swiper-slide-vertical"><img src="{% static 'img/Kepler22.jpg' %}" alt=""></div>
				<div class="swiper-slide-vertical"><img src="{% static 'img/PinkPlanetGJ504b.jpg' %}" alt=""></div>
					</div>
				</div>
			</div>
		</div>
		<div class="buttons">
		<div class="btn1">
			<a href="{% url 'spaceapp:nimro' %}"><img src="{% static 'img/button1.jpg' %}" alt="btn1"/></a>
		</div>
		<div class="btn2">
			<a href="{% url 'spaceapp:chimaira' %}"><img src="{% static 'img/button2.jpg' %}" alt="btn2"/></a>
			</div>
		<div class="btn3">
			<a href="{% url 'spaceapp:tanos' %}"><img src="{% static 'img/button3.jpg' %}" alt="btn3"></a>
		</div>
		<div class="btn4">
			<a href="{% url 'spaceapp:prometheus' %}"><img src="{% static 'img/button4.jpg' %}" alt="btn4"/></a>
		</div>	
	</div>
</div>
<div class="footer">
	<p>Вся информация, представленная на сайте, является вымышленной любые совпадния случайны.
        <p>Designed by SvPr1993</p>
        <p><img src="{% static 'img/logo.png' %}" alt="logo"width="20px" height="20px" style="margin-bottom: -2px"/>ElectroCore spaceapp Project &copy</p>
        </div>
        <div class="images_footer"> 
			<a href="https://www.nasa.gov/"><img src="{% static 'img/nasa_logo.png' %}" alt="nasa" width="55px" height="55px"/></a>
            <a href="https://www.spaceappx.com/"><img src="{% static 'img/space_x_logo.png' %}" alt="space_x_logo" width="65px" height="65px"/></a>
            <a href="https://global.jaxa.jp/"><img src="{% static 'img/jaxa_logo.png' %}" alt="jaxa" width="55px" height="55px"/></a>
            <a href="https://www.esa.int/"><img src="{% static 'img/ESA_logo.png' %}" alt="ESA" width="75px" height="65px"/></a>
    </div>
		  <!-- Swiper JS -->
		  <script src="https://cdn.jsdelivr.net/npm/swiper@9/swiper-bundle.min.js"></script>
		  <script src="https://cdn.jsdelivr.net/npm/swiper@8/swiper-bundle.min.js"></script>
		  <script defer src="{% static 'js/app.js' %}"></script>
		  <script defer src="{% static 'js/script_thumbs.js' %}"></script>
		  <script src="{% static 'js/cirlce.js' %}"></script>
		</div>
</body>
</html>

templates/spaceapp/develops.html
<!DOCTYPE html>
{% load static %}
<html lang="ru">
<head>
    <title>Develops</title>
   <meta charset="UTF-8">
   <meta http-equiv="X-UA-Compatible" content="ie=edge">
   <meta name="viewport" content="width=device-width, initial-scale=1.0">
   <link rel="shortcut icon" href="{% static 'img/favicon.png' %}" type="image/x-icon"/>
   <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/swiper@9/swiper-bundle.min.css" />
   <link rel="stylesheet" type="text/css" href="{% static 'css/style_develops.css' %}"/>
   <script src="https://kit.fontawesome.com/b99e675b6e.js"></script>
</head>
   <body>
    <div class="content-box">
    <header>
        <div class="All_header_menu">
            <div class="logo">
                <a href="{% url 'spaceapp:base' %}"><h1>ElectroCore Space Project</h1></a>
				</div>
            <div class="top_menu">
                <ul>
					<li><a href="{% url 'spaceapp:project' %}">Наш проект</a></li>
					<li><a href="{% url 'spaceapp:develops' %}">Разработки</a></li>
                    <li><a href="{% url 'spaceapp:feedback' %}">Обратная связь</a></li>
                </ul>
			</div>
		</div>
        <div class="wrapper">
			<form action="{% url 'spaceapp:search' %}" method="get">
            <div class="search_box">
				<div class="search_btn"><input type="image" src="{% static 'img/sear_icon.png' %}" alt="search" width="25px" height="25px"/></div>
				<input type="text" class="input_search" placeholder="Поиск">
            </div>
        </div>
	</form>
	</header>
    <div class="background_article">
    <div class="second_background_article">
    <div class="article">
        <img src="{% static 'img/electro_logo.png' %}" alt="electro_logo_img"/>
        <p>Наш проект разрабатывет, обучает и совершенствует ИИ, а также изготовливает и программирует микросборки, процессоры и другие изделия для передовых спутников.
        Разработанное программное обеспечения и собранные микросборки уже успешно применяются в спутниках нового поколения.
        Благодаря нашим разработкам было совершенно несколько открытий в нашей солнечной системе и за ее пределами!</p>
    </div>
    <div class="article_1">
        <img src="{% static 'img/iris.jpg' %}" alt="iris_img" style="margin-top: 10px" "margin-bottom: 10px"/>
        <p>Спутники серии <b>IRIS XX-19</b> работают в качестве телескопа и передают фото и информацию в космические центры на Земле.
        Спутники выведены на орбиту Земли, Марса, Глизе 504b и Кеплер 22b. В спутниках этой серии успешно и надежно функционирую наши микросборки. 
        Основная задача микросборок- это скоростная передача информации и фото без потери качества. Наша разработка признана самой эффективной
        и перспективной!</p>
        <img src="{% static 'img/kit.jpg' %}" alt="kit_img" style="margin-top: 10px" "margin-bottom: 10px"/>
        <p>Спутник <b>KIT ML-2000</b> на данный момент существует единственном экземпляре. Основная его задача это спектральный анализ далеких планет,
        формирование приблизителых ландшафтов планеты, состава атмосферы, температуры поверхности планеты и поиск возможные полезные ископаемые. 
        Мы с особой ответственность подошли к разработке программного обеспечения для данного вида аппаратуры. 
        Проект разработал процессор для подобного рода задач. Процессор разботает при помощи ИИ Chimaira,
        это нужно для того чтобы получать точные данные. Данный тип спутника проанализировал планету GJ504b и мы имеем примерное представление о ее поверхности.</p>
        <img src="{% static 'img/tesa.jpeg' %}" alt="tesa_img" style="margin-top: 10px" "margin-bottom: 10px"/>
        <p>Серия спутников <b>TESA IIX-p</b> производится массово. Их основная задача поиск полезных ископаемых.
        В солнечной системы насчитывается не менее ста функционирующих спутников этого типа. Также эти спутники вывели на орбиты планет лизе 504b и Кеплер 22b
        для поиска полезных ископаемых и формирование данных о приблизительном количестве и типе ископаемых. Мы разработали антенну данного спутника, а также
        обучили ИИ Nimro для реализации данной задачи. Уже сейчас мы в режиме онлайн передаем данный компаниям добывающей промышленности и обсужаем возможные
        варианты развития плана по освоению и добычи ископаемых на новых планетах!
        </p>
    </div>
</div>
</div>
    <div class="footer_develops_page">
        <p>Вся информация, представленная на сайте, является вымышленной любые совпадния случайны.
            <p>Designed by SvPr1993</p>
            <p><img src="{% static 'img/logo.png' %}" alt="logo"width="20px" height="20px" style="margin-bottom: -2px"/>ElectroCore Space Project &copy</p>
            </div>
            <div class="images_footer">
                <a href="https://www.nasa.gov/"><img src="{% static 'img/nasa_logo.png' %}" alt="nasa" width="55px" height="55px"/></a>
                <a href="https://www.spaceappx.com/"><img src="{% static 'img/space_x_logo.png' %}" alt="space_x_logo" width="65px" height="65px"/></a>
                <a href="https://global.jaxa.jp/"><img src="{% static 'img/jaxa_logo.png' %}" alt="jaxa" width="55px" height="55px"/></a>
                <a href="https://www.esa.int/"><img src="{% static 'img/ESA_logo.png' %}" alt="ESA" width="75px" height="65px"/></a>
        </div>
    </body>
    </html>

templates/spaceapp/feedback.html
<!DOCTYPE html>
{% load static %}
<html lang="ru">
<head>
   <title>Feedback</title>
   <meta charset="UTF-8">
   <meta http-equiv="X-UA-Compatible" content="ie=edge">
   <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no»"/>
   <link rel="shortcut icon" href="{% static 'img/favicon.png' %}" type="image/x-icon"/>
   <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/swiper@9/swiper-bundle.min.css" />
   <link rel="stylesheet" type="text/css" href="{% static 'css/style_feedback.css' %}"/>
   <script src="https://kit.fontawesome.com/b99e675b6e.js"></script>
</head>
   <body>
    <div class="content-box">
    <header>
        <div class="All_header_menu">
            <div class="logo">
                <a href="{% url 'spaceapp:base' %}"><h1>ElectroCore Space Project</h1></a>
				</div>
            <div class="top_menu">
                <ul>
					<li><a href="{% url 'spaceapp:project' %}">Наш проект</a></li>
					<li><a href="{% url 'spaceapp:develops' %}">Разработки</a></li>
                    <li><a href="{% url 'spaceapp:feedback' %}">Обратная связь</a></li>
                </ul>
			</div>
		</div>
        <div class="wrapper">
            <form action="{% url 'spaceapp:search' %}" method="get">
            <div class="search_box">
                <input type="image" class="search_btn" src="{% static 'img/sear_icon.png' %}" width="25px" height="25px">
                <input type="search" class="input_search" placeholder="Поиск" font-size="15px">
            </div>
        </div>
    </form>
	</header>
<div class="container">
    <div class="form">
    <h2>Есть вопросы или предложения? Пишите нам!</h2>
    <div class="data_block">
        <input type="text" class="name" placeholder="ФИО/Организация">
        <input type="text" class="mail" placeholder="Email">
        <input type="text" class="phone" placeholder="Телефон">
    </div>
    <div class="text_area">
        <p class="message">Сообщение</p>
        <textarea rows="5" placeholder="Напишите свое сообщение..."></textarea>
    </div>
    <div class="send">
        <button>Отправить</button>
    </div>
</div>
</div>
<div class="footer_feedback_page">
    <p>Вся информация, представленная на сайте, является вымышленной любые совпадния случайны.
        <p>Designed by SvPr1993</p>
        <p><img src="{% static 'img/logo.png' %}" alt="logo" width="20px" height="20px" style="margin-bottom: -2px"/>ElectroCore Space Project &copy</p>
        </div>
    <div class="images_footer"> 
        <a href="https://www.nasa.gov/"><img src="{% static 'img/nasa_logo.png' %}" alt="nasa" width="55px" height="55px"/></a>
            <a href="https://www.spaceappx.com/"><img src="{% static 'img/space_x_logo.png' %}" alt="space_x_logo" width="65px" height="65px"/></a>
            <a href="https://global.jaxa.jp/"><img src="{% static 'img/jaxa_logo.png' %}" alt="jaxa" width="55px" height="55px"/></a>
            <a href="https://www.esa.int/"><img src="{% static 'img/ESA_logo.png' %}" alt="ESA" width="75px" height="65px"/></a>
    </div>
</div>
</body>
</html>

templates/spaceapp/project.html
<!DOCTYPE html>
{% load static %}
<html lang="ru">
<head>
   <meta charset="UTF-8">
   <meta http-equiv="X-UA-Compatible" content="ie=edge">
   <meta name="viewport" content="width=device-width, initial-scale=1.0">
   <link rel="shortcut icon" href="{% static 'img/favicon.png' %}" type="image/x-icon"/>
   <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/swiper@9/swiper-bundle.min.css" />
   <title>Project</title>
   <link rel="stylesheet" type="text/css" href="{% static 'css/style_project.css' %}"/>
   <script src="https://kit.fontawesome.com/b99e675b6e.js"></script>
</head>
   <body>
    <div class="content-box">
    <header>
        <div class="All_header_menu">
            <div class="logo">
                <a href="{% url 'spaceapp:base' %}"><h1>ElectroCore Space Project</h1></a>
				</div>
            <div class="top_menu">
                <ul>
					<li><a href="{% url 'spaceapp:project' %}">Наш проект</a></li>
					<li><a href="{% url 'spaceapp:develops' %}">Разработки</a></li>
                    <li><a href="{% url 'spaceapp:feedback' %}">Обратная связь</a></li>
                </ul>
			</div>
		</div>
        <div class="wrapper">
            <div class="search_box">
                <div class="search_btn"><input type="image" src="{% static 'img/sear_icon.png' %}" alt="search" width="25px" height="25px"/></div>
                <input type="text" class="input_search" placeholder="Поиск">
            </div>
        </div>
	</header>
    <div class="background_article">
        <div class="article">
            <img src="{% static 'img/office.jpg' %}" alt="office_img" style="margin-bottom: 10px"/>
          <p><b>Electrocore Space Project</b> - это перспективный международный проект, который занимается сопровождением космических экспедиций.</p>
          <p>Нашей визитной карточкой является разработка искусственных интелектов Nimro и Chimaira.
            ИИ Nirmo предназначен для сопрождения исследований на относительно небольшие расстояния,
            ИИ Chimaira, наоборот, разработана для исследований так сказать в "неизвестность".
            Оба ИИ отлично проявили себя в ходу испытаний. ИИ Nimro успешно сопровождал экспедиции на Марс и Плутон, а также анализировал спектральный анализ Глизе 581с.
            ИИ Chimaira анализировала и передавала точные данный со спутников о других планетах, в частности благодаря данному ИИ удалось открыть уникальную парктически 
            вертикальную гору на планете Кеплер 22b.
            Мы сотрудничаем с организациям NASA, SpaceX, ESA, JAXA, KARI, SSTL.
            Наши представительства работаю в США, ЕС, ОАЭ, Сингапуре, Южной Корее, Японии и Австралии.</p>
        </div>
</div>
<div class="footer_project_page">
<p>Вся информация, представленная на сайте, является вымышленной любые совпадния случайны.
    <p>Designed by SvPr1993</p>
    <p><img src="{% static 'img/logo.png' %}" alt="logo"width="20px" height="20px" style="margin-bottom: -2px"/>ElectroCore Space Project &copy</p>
    </div>
    <div class="images_footer"> 
        <a href="https://www.nasa.gov/"><img src="{% static 'img/nasa_logo.png' %}" alt="nasa" width="55px" height="55px"/></a>
        <a href="https://www.spaceappx.com/"><img src="{% static 'img/space_x_logo.png' %}" alt="space_x_logo" width="65px" height="65px"/></a>
        <a href="https://global.jaxa.jp/"><img src="{% static 'img/jaxa_logo.png' %}" alt="jaxa" width="55px" height="55px"/></a>
        <a href="https://www.esa.int/"><img src="{% static 'img/ESA_logo.png' %}" alt="ESA" width="75px" height="65px"/></a>
</div>
</body>
</html>

templates/spaceapp/search.html
<!DOCTYPE html>
{% load static %}
<html lang="ru">
<head>
   <title>ElectroCore Space Project</title>
   <meta charset="UTF-8">
   <meta http-equiv="X-UA-Compatible" content="ie=edge">
   <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no»"/>
   <link rel="shortcut icon" href="{% static 'img/favicon.png' %}" type="image/x-icon"/>
   <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/swiper@9/swiper-bundle.min.css" />
   <link rel="stylesheet" type="text/css" href="{% static 'css/styles.css' %}"/>
   <script src="https://kit.fontawesome.com/b99e675b6e.js"></script>
</head>
   <body>
    <div class="content-box">
    <header>
        <div class="All_header_menu">
            <div class="logo">
                <a href="{% url 'spaceapp:base' %}"><h1>ElectroCore Space Project</h1></a>
				</div>
            <div class="top_menu">
                <ul>
					<li><a href="{% url 'spaceapp:project' %}">Наш проект</a></li>
					<li><a href="{% url 'spaceapp:develops' %}">Разработки</a></li>
                    <li><a href="{% url 'spaceapp:feedback' %}">Обратная связь</a></li>
                </ul>
			</div>
		</div>
        <div class="wrapper">
			<form action="{% url 'spaceapp:search' %}" method="get">
            <div class="search_box">
				<div class="search_btn"><input type="image" src="{% static 'img/sear_icon.png' %}" alt="search" width="25px" height="25px"/></div>
            </div>
        </div>
	</form>
	</header>
	<div class="background_base"></div>